export const JWT_SECRET_KEY = 'JWT_SECRET';
export const PASSWORD_CRYPTO_SECRET_KEY = 'PASSWORD_CRYPTO_SECRET';
export const FIREBASE_PROJECT_ID_KEY = 'FIREBASE_PROJECT_ID';
export const FIREBASE_CLIENT_EMAIL_KEY = 'FIREBASE_CLIENT_EMAIL';
export const FIREBASE_PRIVATE_KEY_KEY = 'FIREBASE_PRIVATE_KEY';
