export const JWT_SECRET_KEY = 'JWT_SECRET';
export const PASSWORD_CRYPTO_SECRET_KEY = 'PASSWORD_CRYPTO_SECRET';
export const MOBILE_APP_MIN_SUPPORTED_VERSION =
	'MOBILE_APP_MIN_SUPPORTED_VERSION';
export const MOBILE_APP_LINK_TO_GOOGLE_PLAY = 'MOBILE_APP_LINK_TO_GOOGLE_PLAY';
export const MOBILE_APP_LINK_TO_APP_STORE = 'MOBILE_APP_LINK_TO_APP_STORE';
export const IS_ENABLED_SCHEDULER_UPDATE_SUBJECTS =
	'IS_ENABLED_SCHEDULER_UPDATE_SUBJECTS';
