export const PORT_KEY = 'PORT';
export const LOG_FILE_PATH_KEY = 'LOG_FILE_PATH';
export const JWT_SECRET_KEY = 'JWT_SECRET';
export const MOBILE_APP_MIN_SUPPORTED_VERSION_KEY = 'MOBILE_APP_MIN_SUPPORTED_VERSION';
export const MOBILE_APP_LINK_TO_GOOGLE_PLAY_KEY = 'MOBILE_APP_LINK_TO_GOOGLE_PLAY';
export const MOBILE_APP_LINK_TO_APP_STORE_KEY = 'MOBILE_APP_LINK_TO_APP_STORE';
