export const JWT_SECRET_KEY = 'JWT_SECRET';
export const PASSWORD_CRYPTO_SECRET_KEY = 'PASSWORD_CRYPTO_SECRET';
export const MOBILE_APP_MIN_SUPPORTED_VERSION_KEY =
	'MOBILE_APP_MIN_SUPPORTED_VERSION';
export const MOBILE_APP_LINK_TO_GOOGLE_PLAY_KEY =
	'MOBILE_APP_LINK_TO_GOOGLE_PLAY';
export const MOBILE_APP_LINK_TO_APP_STORE_KEY = 'MOBILE_APP_LINK_TO_APP_STORE';
export const IS_ENABLED_SCHEDULER_UPDATE_SUBJECTS_KEY =
	'IS_ENABLED_SCHEDULER_UPDATE_SUBJECTS';
